{"name": "Получение ошибки приема заказа с некорректным id курьера", "status": "passed", "description": "Проверка принятия заказа с неверным id курьера | GET /api/v1/orders/track", "start": 1703754072592, "stop": 1703754074071, "uuid": "7643b459-0cfa-402b-a685-7d4754a52946", "historyId": "0fcf608edd33a180c96579a967433320", "testCaseId": "0fcf608edd33a180c96579a967433320", "fullName": "tests.test_create_order.TestGetOrder#test_get_order_with_bad_courier_id_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "Redmi6-Redmi6"}, {"name": "thread", "value": "5034-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}