{"name": "Получение ошибки данных о несуществующем заказе", "status": "passed", "description": "Проверка получения данных о заказе с несуществующим номером | GET /api/v1/orders/track", "start": 1703754066307, "stop": 1703754066635, "uuid": "9e83a8c6-57ce-47fd-8d85-4bb26ae8c9b4", "historyId": "9815295de1dd8ba42998df8f181e9c2f", "testCaseId": "9815295de1dd8ba42998df8f181e9c2f", "fullName": "tests.test_create_order.TestTrackingOrder#test_order_track_bad_order_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestTrackingOrder"}, {"name": "host", "value": "Redmi6-Redmi6"}, {"name": "thread", "value": "5034-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}